# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb1d883997f63b46bb50212b6ee4c9a48dcd1afab7977fc3497311259ad5a269ef4c476e95bc591170c830b483ceaeb584a75cf71301069fe7ded9beab6ce35

test:
  secret_key_base: f97150cc8e85f356b8324fdaf2d2b5448642d8e7e80242b1234a4e5b1b5c6702894345869815c03cbd360095dcf83ee1ca14f995a3d2dc2bf96357e58d448bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
